### ISSUE TITLE
Z Offset plugin in Cura

### ISSUE THREAD

**Issue by Canabl3d** [fieldOfView/ZOffsetPlugin#8] opened 2019-11-20 18:49 UTC
I have an Anycubic predator and I have come up with an odd issue that I believe your Z Offset plugin for cura (which I love and think is an absolute necessity) is causing it. 
In cura using any variation of the draft 0.2 profile works great for printing.... If I switch to the Normal 0.15 profile or 0.06, my predator goes to the glass to start to print and then the head goes AWOL every time...it lifts off the glass and starts to print in the air in at all different angles and heights... But if I switch back to a 0.2 profile again (custom or standard) it works fine.... 

After hours of troubleshooting I found the issue. It is caused by the Z Offset plugin which I have used for a few months and really like. I guess with the update to Cura 4.3 the plugin works fine on layer settings 0.2 but if it is any smaller my predator printer goes rogue. If I set it to 0 everything works great using any profile layer height but then I have bed adhesion issues.  Cura 4.4 does the same thing.

Is there more information that I can give you to help fix the plugin. It is something that I use all the time. 

thank you so much for the work you put into the  it is a huge benefit to us new to 3d printers

Cheers
Michael

**Comment by fieldOfView** [comment] 2019-11-21 08:51
Seems to be a duplicate of #7

**Closed as completed by fieldOfView** 2019-11-21 08:51 UTC
