### ISSUE TITLE
Z-Offset in Per Model Settings

### ISSUE THREAD

**Issue by reinew** [fieldOfView/ZOffsetPlugin#39] opened 2024-01-06 17:55 UTC
I like to be able to set separate Z-offsets with the "Per Model Settings" option to be able to test different offsets on different test patches but the option is not visible? I have checked the "Show all" checkbox and i already have all options visible under Setting Visibility. I'm running Cura v5.5.0.

**Comment by fieldOfView** [comment] 2024-01-06 19:51
Duplicate of #34 

This would lead to multiple different Z heights within one layer, with a high potential of bumping the nozzle into already printer parts while traveling. It may sound like a simple thing to add, but it isn't.

**Closed as completed by fieldOfView** 2024-01-06 19:51 UTC
